version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_OPTIONS: "--max-old-space-size=1006"
    volumes:
      - .:/usr/src/app
    command: ["npm", "start"]